### ISSUE TITLE
Device-side error when using k2 ctc

### ISSUE THREAD

**Issue by brianyan918** [zhu-han/espnet-k2#1]
Hi!

I made my way here from: https://github.com/k2-fsa/k2/issues/575#issuecomment-756809170

I just tried to run your k2 implementation, but got this error:
`RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered`

The problem seems to be coming from this line in forward() from ctc_graph.py:
`tot_scores = k2.get_tot_scores(target_graph,
                                   log_semiring=True,
                                   use_double_scores=True)`

Did you perhaps encounter this and already fix it locally?

**Comment by brianyan918** [comment]
update:

I was able to run the CTC portion on CPU. Were you running it on GPU?

**Comment by zhu-han** [comment]
Yes, I was running it on GPU and did not encounter this error before.

**Comment by zhu-han** [comment]
Is your k2 compiled correctly? Have you tried to run tests after build k2 or run the snowfall examples to make sure it works fine?

**Comment by brianyan918** [comment]
Yes all the tests passed. I have not tried the snowfall example though.

**Comment by zhu-han** [comment]
I checked my code and run it again but could not reproduce this bug.  I don't know what could lead to this error.

**Comment by zhu-han** [comment]
I used librispeech 100h with bpe 5000 as the modeling unit for my experiments.  And I used PyTorch 1.7 and CUDA 10.1 to run this code. Not sure if this bug related to the environment setup.

**Comment by zhu-han** [comment]
@brianyan918 Have you solved this problem? If not, maybe I could help more if you could share the Implementation details of how you used the k2 CTC loss.

**Comment by brianyan918** [comment]
I used your implementation, but my environment is pytorch 1.6 and cuda 10.2. I'll examine the error more thoroughly, but for now I was able to run this on CPU instead.
